# -*- coding: utf-8 -*-
"""gamemodelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SeAoUhc49mTsoQ7ip46_uTLU_Ux2UOL_

# NINTENDO GAME SALES PREDICTIVE MODELLING
"""

# Importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# loading csv
df = pd.read_csv('/content/cleanvgdata.csv')
df.head(20)

"""# EDA PHASE"""

# column statistic
df.describe()

df.info()

df.shape

# checking for null values
df.isnull().sum()

"""This confirms the data set was cleaned using sql as there are no columns with null values

# VISUALIZATIONS
"""

#  Histogram/ Visualization
df.hist(figsize=(20,20) )

# Filter for Nintendo games and relevant years (2010-2016)
nintendo_df = df[(df['publisher'] == 'Nintendo') & (df['year'].between(2010, 2016))].copy()
industry_df = df[df['year'].between(2010, 2016)].copy()

# Convert year to integer
nintendo_df['year'] = nintendo_df['year'].astype(int)
industry_df['year'] = industry_df['year'].astype(int)

print(f"Nintendo data rows after filtering: {nintendo_df.shape[0]}")
print(f"Industry data rows after filtering: {industry_df.shape[0]}")

"""# --- 2. KPI ANALYSIS ---

"""

# **Q1: How has Nintendo’s market share evolved annually?**
# Calculate annual global sales for Nintendo and the entire industry
nintendo_annual_sales = nintendo_df.groupby('year')['global_sales'].sum().reset_index()
industry_annual_sales = industry_df.groupby('year')['global_sales'].sum().reset_index()

# Merges and calculate market share
market_share_df = nintendo_annual_sales.merge(
    industry_annual_sales, on='year', suffixes=('_nintendo', '_industry')
)
market_share_df['market_share'] = (market_share_df['global_sales_nintendo'] / market_share_df['global_sales_industry']) * 100

print("\n--- Nintendo Annual Market Share (2010-2016) ---")
print(market_share_df[['year', 'market_share']].to_markdown(index=False, numalign="left", stralign="left"))

# Plot market share evolution
plt.figure()
sns.lineplot(x='year', y='market_share', data=market_share_df, marker='o', color='red')
plt.title('Nintendo Global Market Share (2010-2016)', fontsize=16)
plt.xlabel('Year')
plt.ylabel('Market Share (%)')
plt.xticks(market_share_df['year'])
plt.grid(True)
plt.show()

# **Q2: Which genres (top 3 annually) drove outsized performance?**
print("\n--- Top 3 Nintendo Genres by Global Sales per Year ---")
top_genres_by_year = nintendo_df.groupby(['year', 'genre'])['global_sales'].sum().reset_index()
top_genres_by_year['rank'] = top_genres_by_year.groupby('year')['global_sales'].rank(method='first', ascending=False)
top_genres = top_genres_by_year[top_genres_by_year['rank'] <= 3].sort_values(by=['year', 'rank'])

print(top_genres[['year', 'genre', 'global_sales']].to_markdown(index=False, numalign="left", stralign="left"))

# **Q3: Which regions contribute most to sales?**
regional_sales = nintendo_df[['na_sales', 'eu_sales', 'jp_sales', 'other_sales']].sum()
print("\n--- Total Regional Sales Contribution (2010-2016) ---")
print(regional_sales.sort_values(ascending=False).to_markdown(numalign="left", stralign="left"))

# Plot regional sales contribution
plt.figure()
regional_sales.plot(kind='bar', color=['#008080', '#DDA0DD', '#90EE90', '#FFB6C1'])
plt.title('Nintendo Regional Sales Contribution (2010-2016)', fontsize=16)
plt.xlabel('Region')
plt.ylabel('Total Sales (in millions)')
plt.xticks(rotation=0)
plt.grid(axis='y')
plt.show()